flyway.locations=filesystem:migrations/sql
flyway.url=jdbc:postgresql://${env.ERP_DATABASE_HOST}:${env.ERP_DATABASE_PORT}/${env.ERP_DATABASE_NAME}
flyway.user=${env.ERP_DATABASE_USER}
flyway.password=${env.ERP_DATABASE_PASSWORD}
flyway.schemas=iam,crm,sales,inventory,purchasing,accounting,banking,hr
flyway.defaultSchema=iam
